### ISSUE TITLE
Install Binaries command fail

### ISSUE THREAD

**Issue by BeastlyGabi** [geode-sdk/cli#10]
I followed all the steps on the [installation guide](https://docs.geode-sdk.org/installation/#for-users) but when getting to the `install-binaries` command step, this happens
![image](https://user-images.githubusercontent.com/93128334/221621080-1446c079-8f44-464e-9df6-d3e559f90721.png)

any idea why?

**Comment by BeastlyGabi** [comment]
thanks for the quick response and I will be looking forward to it

**Comment by HJfod** [comment]
Hey, I [made the release](https://github.com/geode-sdk/geode/releases/tag/v1.0.0-beta.8). Try rerunning the command

**Comment by BeastlyGabi** [comment]
![image](https://user-images.githubusercontent.com/93128334/221623243-71d66017-d145-4302-9334-8fe6e7493530.png)
it works, thanks!
