### ISSUE TITLE
Config setup doesn't recognize Geometry Dash folder

### ISSUE THREAD

**Issue by Omay238** [geode-sdk/cli#13]
I am on an M1 Mac, and my Geometry Dash folder is `/Users/omay/Library/Application\ Support/Steam/steamapps/common/Geometry\ Dash`. I get the error `The path must point to the Geometry Dash folder, not the executable` while running `geode config setup`. How can I fix this?

**Comment by TheBearodactyl** [comment]
try using quotes instead of escaping the spaces
