### ISSUE TITLE
`| Fail | Invalid SDK version: unexpected character '\r' after patch version number`

### ISSUE THREAD

**Issue by TechStudent10** [geode-sdk/cli#15]
After attempting to create a new mod (after running `geode sdk update`), I get the following results:

![image](https://github.com/geode-sdk/cli/assets/76978184/46660ed6-28b9-498a-a5c1-869f7963104f)

**Comment by matcool** [comment]
will fix asap, dont know why cli doesnt trim the version

**Comment by matcool** [comment]
fixed in v2.4.2

**Comment by TechStudent10** [comment]
Thanks, will update

**Comment by TechStudent10** [comment]
Works now 👍🏾
