### ISSUE TITLE
Incompatible with M1 Macs

### ISSUE THREAD

**Issue by SonicRay241** [geode-sdk/cli#2]
It seems that geode cli for mac haven't been updated to support arm64 architecture yet, as seen in this error:
<img width="803" alt="Screen Shot 2022-05-12 at 4 07 33 PM" src="https://user-images.githubusercontent.com/92853267/168023379-44871ab2-bb4c-4103-b30d-df80403f270f.png">

Please make a separate installer for arm64 and x86 based macs for future releases.

**Comment by camila314** [comment]
compile with `export OPENSSL_STATIC=1`
