### ISSUE TITLE
How to use

### ISSUE THREAD

**Issue by realhackcraft** [geode-sdk/cli#3]
I don't understand what you do after you download the release. There should be a wiki page or something.

**Comment by camila314** [comment]
we should bring public shaming back into popularity

**Comment by spookybear0** [comment]
Is this really necessary, like, you could just show them the documentation.

**Comment by camila314** [comment]
read the EULA section 1.3, it is absolutely necessary and I will do it to you too

**Comment by altalk23** [comment]
Tbh no one knows how to use the cli just write geode help to the console

**Comment by realhackcraft** [comment]
bruh i just figured out how to use

**Comment by realhackcraft** [comment]
it doesn't say how I move CLI to PATH on mac. When I run the `geode` command, iTerm says it doesn't exist.

**Comment by realhackcraft** [comment]
:warning: Note: this section is for Windows.
where is the section for mac

**Comment by camila314** [comment]
there's actually a pretty cool website I found that explains it quite well: https://google.com/search?q=add+executable+to+path+mac

**Comment by camila314** [comment]
both

**Comment by realhackcraft** [comment]
it says `zsh: permission denied: geode`

**Comment by prokube** [comment]
> ⚠️ Note: this section is for Windows.
> where is the section for mac

this reminds me i have to pr this now
