### ISSUE TITLE
Issue with adding CLI to PATH

### ISSUE THREAD

**Issue by TechStudent10** [geode-sdk/cli#4]
I don't know why this is happening.

I was following the instructions [**here**](https://geode-sdk.github.io/docs/#/docs/info/installation?id=using-geode-cli). I got the executable, added it to it's own separate folder, then added it to the PATH environment variable for my user account.

When I go ahead and try running `geode` or `geode config setup`, I get this:

![image](https://user-images.githubusercontent.com/76978184/200194155-74ca4ce6-578f-4e3e-aad4-0b3084511e4f.png)

I found this weird. I looked back in my environment variables and there they were. I am sure I copied the path correctly.

![image](https://user-images.githubusercontent.com/76978184/200194213-a6e86a6e-8ad3-46e5-a7b4-9cc39667d3d2.png)

I used the commands `echo %path%` and just `PATH` in all uppercases to see if it had even applied.

![image](https://user-images.githubusercontent.com/76978184/200194253-e4145f31-e658-4971-b966-b876c8b05e7b.png)

```
PATH=C:\Program Files\ImageMagick-7.1.0-Q16-HDRI;C:\Program Files\Eclipse Adoptium\jdk-11.0.14.101-hotspot\bin;C:\Program Files (x86)\VMware\VMware Player\bin\;C:\Program Files\Common Files\Oracle\Java\javapath;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\ProgramData\Oracle\Java\javapath;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files\Git\cmd;C:\ProgramData\chocolatey\bin;C:\Program Files\dotnet\;C:\Users\moham\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\Scripts;C:\Users\moham\AppData\Local\Microsoft\WindowsApps;C:\Users\moham\AppData\Local\Programs\Microsoft VS Code\bin;C:\Users\moham\AppData\Roaming\npm;C:\Users\moham\AppData\Local\GitHubDesktop\bin;C:\Users\moham\AppData\Local\atom\bin;C:\flutter\bin;C:\Program Files\heroku\bin;C:\Users\moham\bin;C:\Users\moham\AppData\Local\Android\Sdk\tools;C:\Users\;C:\Program Files\Docker\Docker\resources\bin;C:\ProgramData\DockerDesktop\version-bin;C:\Program Files (x86)\spwn\;C:\Program Files\nodejs\;C:\Program Files\Neovim\/bin;C:\Program Files\Rust stable GNU 1.62\bin;C:\tools\gsudo\Current;C:\Users\moham\geode\geode.exe;;C:\Users\moham\.cargo\bin;C:\Users\moham\AppData\Local\Programs\Python\Python310\Scripts\;C:\Users\moham\AppData\Local\Programs\Python\Python310\;C:\Users\moham\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\Scripts;C:\Users\moham\AppData\Local\Microsoft\WindowsApps;C:\Users\moham\AppData\Local\Programs\Microsoft VS Code\bin;C:\Users\moham\AppData\Local\atom\bin;C:\flutter\bin;C:\Users\moham\bin;C:\Users\moham\AppData\Local\Android\Sdk\tools;C:\Users\moham\AppData\Local\Android\Sdk\platform-tools;C:\Program Files (x86)\GitHub CLI\;C:\Users\moham\AppData\Local\Microsoft\WindowsApps;C:\Users\moham\AppData\Local\Programs\Hyper\resources\bin;C:\Program Files\VideoLAN\VLC;C:\Program Files (x86)\spwn;C:\Users\moham\AppData\Roaming\npm;C:\Program Files\CMake\bin;C:\Users\moham\geode\geode.exe;
```

At the end, the path to Geode is visible. Even after using the `refreshenv` command built into (I think) Chocolatey, rebooting my computer, using different versions of Windows Terminal (Normal and Preview) and using plain `cmd.exe` altogether, I still cannot get Geode to run.

**Comment by TechStudent10** [comment]
As a workaround, I am just going to have to run Geode from that one specific folder(s).

**Comment by HJfod** [comment]
The path has to point to the directory with `geode.exe`, not the exe itself (i.e. change it to `C:\Users\moham\geode`). I'll make this clearer in the docs

**Comment by TechStudent10** [comment]
Ah I feel so dumb for forgetting it. Thanks.

**Comment by TechStudent10** [comment]
@HJfod maybe you should also update the steps for installing the Geode CLI and SDK. You first need to run `geode sdk install` then set the GEODE_SDK environment variable if the command didn't do so already. Then you can run `geode config setup` without and errors. Then `geode sdk install-binaries` and done.
