### ISSUE TITLE
geode sdk install-binaries trying to download a nonexistent version

### ISSUE THREAD

**Issue by KontrollFreek** [geode-sdk/cli#41]
does not work on nightly or stable but nightly is a bit more unclear as to what it's doing wrong
![image](https://github.com/geode-sdk/cli/assets/72424960/2156a832-27bf-4562-bd32-7a7287b03b3b)
![image](https://github.com/geode-sdk/cli/assets/72424960/0eb46dc1-2187-492c-8459-a326ce54a189)

**Comment by matcool** [comment]
do you get this *every* time? this is the same error CI builds sometimes have, and are fixed by just trying again

**Comment by KontrollFreek** [comment]
every single time. i've even tried completely uninstalling the sdk and installing it again (`geode sdk uninstall` gets funky because of env variables on windows but i just removed the Geode folder and deleted `GEODE_SDK`)

**Comment by KontrollFreek** [comment]
nvm i fixed it because i was using v1.1.0 of the cli for some reason 🔥 idk why i didn't check
