### ISSUE TITLE
Geode mod not building/Nonexistent command in build

### ISSUE THREAD

**Issue by TechStudent10** [geode-sdk/cli#5]
I went ahead and followed the steps in the docs. I opened VSCode, installed both `C/C++` and `CMake Tools`. When I configured the project, CMake errored out with this to say:

![image](https://user-images.githubusercontent.com/76978184/200200109-6fb778e5-22d0-4678-b87a-f95158f13ddd.png)

I tried running the above command, but it didn't work.

**Comment by TechStudent10** [comment]
And no, running `geode sdk install-binaries` (without the path at the end) doesn't solve the issue.

**Comment by camila314** [comment]
Remove `set(GEODE_LINK_NIGHTLY ON)` from the root CMakeLists.txt file of your project, see if that works

**Comment by TechStudent10** [comment]
Yep that worked. Thanks!

**Comment by TechStudent10** [comment]
@camila314 I'm getting the error again after updating. `geode sdk install-prebuilts` isn't a command, and there is no `set(GEODE_LINK_NIGHTLY ON)` in the `CMakeLists.txt`.
![image](https://user-images.githubusercontent.com/76978184/216358828-41e57ccc-a4d8-4b1e-a44f-91b0ff74a0ee.png)

**Comment by HJfod** [comment]
The `install-prebuilts` command is currently wrong, as it installs Geode to a `v1.0.0-beta` folder whereas CMake looks for it in `v1.0.0`. We will fix this soon

**Comment by TechStudent10** [comment]
> The `install-prebuilts` command is currently wrong, as it installs Geode to a `v1.0.0-beta` folder whereas CMake looks for it in `v1.0.0`. We will fix this soon

So I can't make mods until this is fixed?

**Comment by TechStudent10** [comment]
And `install-prebuilts` does literally nothing. It doesn't exist.

![image](https://user-images.githubusercontent.com/76978184/216360866-6983280b-0951-4f3b-91ab-772bee3f5e6d.png)

**Comment by HJfod** [comment]
Oh whoops, seems like the CMake has the wrong command name. The correct command is `geode sdk install-binaries`.

**Comment by TechStudent10** [comment]
> Oh whoops, seems like the CMake has the wrong command name. The correct command is `geode sdk install-binaries`.

Alright. So I just have to rename it as a temporary workaround?

**Comment by HJfod** [comment]
Yeah, I'm currently pushing a fix for CLI that should be out in a few minutes

**Comment by TechStudent10** [comment]
Alright. Thanks.

FYI for anyone experiencing this bug you need to go to `{GEODE_SDK}/bin` and remove `-beta` until the bug is resolved.
