### ISSUE TITLE
geode sdk not installed

### ISSUE THREAD

**Issue by TymTymXD** [geode-sdk/cli#62]
i ran `geode sdk install` and restarted the terminal and restarted my pc but when i tried to run other commands (sutch like `geode sdk install-binaries`) it says this:
![Screenshot from 2024-06-19 16-07-33](https://github.com/geode-sdk/cli/assets/134377242/f979ee84-0494-49f8-ac9c-9ba553e88560)

**Comment by matcool** [comment]
the env var isnt set. go set it yourself manually or try again with latest cli (it added support for linux)
