### ISSUE TITLE
Error configuring CMake for geode

### ISSUE THREAD

**Issue by aloafofbread812** [geode-sdk/cli#68]
The error is; "CMake Error at CMakeLists.txt:16 (project): Generator Unix Makefiles does not support platform specification, but platform x64 was specified." 
![image](https://github.com/geode-sdk/cli/assets/172190992/6a6d9861-5ccd-4099-bf42-b35af206fbfc)

**Comment by iNUCi** [comment]
Why are you using makefiles. Install ninja.

**Comment by aloafofbread812** [comment]
i dont use android

**Comment by iNUCi** [comment]
> i dont use android

What does that have to do with android????? Install ninja build
