### ISSUE TITLE
geode build not working

### ISSUE THREAD

**Issue by TymTymXD** [geode-sdk/cli#72]
![Screenshot from 2024-07-14 11-55-02](https://github.com/user-attachments/assets/87cf010a-451f-4a6c-a43b-b292d57783a2)
![Screenshot from 2024-07-14 11-54-45](https://github.com/user-attachments/assets/6ebb9ec8-b610-45f4-a824-933505534bee)

**Comment by dankmeme01** [comment]
have you tried running `geode sdk install-linux` beforehand?this is required to install all of the cross-compilation tools

**Comment by TymTymXD** [comment]
yes

**Comment by dankmeme01** [comment]
1. install clang and lld (on Ubuntu this would be `sudo apt install clang-17 clang-tools-17 lld-17`, on other systems might be different)
2. try the geode CLI build from [this github action](https://github.com/geode-sdk/cli/actions/runs/9927535916), there's a small oversight in the released version, and run `geode sdk install-linux` again

**Comment by TymTymXD** [comment]
still not working
![Screenshot from 2024-07-14 14-39-53](https://github.com/user-attachments/assets/5794b054-15bf-48ef-ac9e-d8db94b1c859)
![Screenshot from 2024-07-14 14-39-27](https://github.com/user-attachments/assets/5829427e-f1f4-46d1-af97-eb18ca72d305)

**Comment by dankmeme01** [comment]
can you post the output of `geode sdk install-linux`?

**Comment by TymTymXD** [comment]
![image](https://github.com/user-attachments/assets/056c3ce4-7fb8-4d1f-b925-dcb1733de0d1)

**Comment by dankmeme01** [comment]
can you run it with the `--update-winsdk` argument and post the output again

**Comment by TymTymXD** [comment]
![image](https://github.com/user-attachments/assets/4a008f5d-afec-4843-ba80-98fd7d85c53d)

**Comment by TymTymXD** [comment]
i ran `Geode build` and everything seems to be working now

**Comment by dankmeme01** [comment]
alright, closing then
