### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by BurhanYasir123** [geode-sdk/cli#74]
-- Building for: Visual Studio 17 2022
-- Selecting Windows SDK version 10.0.20348.0 to target Windows 10.0.19045.
-- The C compiler identification is MSVC 19.40.33813.0
-- The CXX compiler identification is MSVC 19.40.33813.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: E:/Program Files (x86)/Microsoft Visual Studio/2022/BuildTools/VC/Tools/MSVC/14.40.33807/bin/Hostx64/x86/cl.exe - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: E:/Program Files (x86)/Microsoft Visual Studio/2022/BuildTools/VC/Tools/MSVC/14.40.33807/bin/Hostx64/x86/cl.exe - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found Geode: C:\Users\dell\Documents\Geode
-- Version: 2.0.0, tag: beta.25 (type: Beta, number: 25)
-- No override path for bindings provided, using CPM to clone default. If you would like to use a separate clone of the bindings repo (for example in order to be able to efficiently change and contribute new bindings) then set GEODE_BINDINGS_REPO_PATH to where you have cloned the repository (system environment variables are supported).
-- CPM: Adding package bindings@ (main)
-- Looking for ccache/sccache
-- Looking for ccache/sccache - skipped (Visual Studio generator)
Not using a caching compiler (ccache/sccache). It is recommended to install one to improve build times.
We recommend sccache, check its README for installation instructions, normally you can just use your usual package manager (e.g. 'scoop install sccache').
Because of this, PCH will be enabled.
-- Pre-compiled headers - ON
-- Found Geode CLI: C:/Users/dell/scoop/shims/geode.exe (version 2.13.1)
-- CPM: Adding package json@28 (28f157b)
-- CPM: Adding package fmt@10.1.1 (10.1.1)
-- Version: 10.1.0
-- Build type: RelWithDebInfo
-- CPM: Adding package filesystem@3 (3e5b930)
-- System name: Windows
-- Compiler ID: MSVC
-- CMAKE_CXX_COMPILE_FEATURES: cxx_std_98;cxx_template_template_parameters;cxx_std_11;cxx_alias_templates;cxx_alignas;cxx_alignof;cxx_attributes;cxx_auto_type;cxx_constexpr;cxx_decltype;cxx_decltype_incomplete_return_types;cxx_default_function_template_args;cxx_defaulted_functions;cxx_defaulted_move_initializers;cxx_delegating_constructors;cxx_deleted_functions;cxx_enum_forward_declarations;cxx_explicit_conversions;cxx_extended_friend_declarations;cxx_extern_templates;cxx_final;cxx_func_identifier;cxx_generalized_initializers;cxx_inheriting_constructors;cxx_inline_namespaces;cxx_lambdas;cxx_local_type_template_args;cxx_long_long_type;cxx_noexcept;cxx_nonstatic_member_init;cxx_nullptr;cxx_override;cxx_range_for;cxx_raw_string_literals;cxx_reference_qualified_functions;cxx_right_angle_brackets;cxx_rvalue_references;cxx_sizeof_member;cxx_static_assert;cxx_strong_enums;cxx_thread_local;cxx_trailing_return_types;cxx_unicode_literals;cxx_uniform_initialization;cxx_unrestricted_unions;cxx_user_literals;cxx_variadic_macros;cxx_variadic_templates;cxx_std_14;cxx_aggregate_default_initializers;cxx_attribute_deprecated;cxx_binary_literals;cxx_contextual_conversions;cxx_decltype_auto;cxx_digit_separators;cxx_generic_lambdas;cxx_lambda_init_captures;cxx_relaxed_constexpr;cxx_return_type_deduction;cxx_variable_templates;cxx_std_17;cxx_std_20;cxx_std_23
-- CPM: Adding package TulipHook@7 (7fa328b)
-- CPM: TulipHook: Adding package result@ (a97e66b)
-- Performing Test SUPPORTS_W_NO_EVERYTHING
-- Performing Test SUPPORTS_W_NO_EVERYTHING - Failed
-- Downloading Codegen
Set SKIP_BUILDING_CODEGEN to OFF to force codegen to build locally.
-- Downloading Codegen - success
-- Skipping building Codegen
-- Running Codegen
'./Codegen' 'Win32' 'C:/Users/dell/Desktop/mod/my_mod/build/_deps/bindings-src/bindings/2.204' 'C:/Users/dell/Desktop/mod/my_mod/build/bindings/bindings'
-- Setting up my_mod
-- Mod burhanyasir.my_mod is compiling for Geode version 2.0.0-beta.25
-- Configuring done (240.1s)
-- Generating done (2.8s)
-- Build files have been written to: C:/Users/dell/Desktop/mod/my_mod/build
MSBuild version 17.10.4+10fbfbf2e for .NET Framework

  1>Checking Build System
  Building Custom Rule C:/Users/dell/Documents/Geode/CMakeLists.txt
  FilesystemImpl.cpp
  GeodeFilesystemImpl.vcxproj -> C:\Users\dell\Desktop\mod\my_mod\build\geode\RelWithDebInfo\GeodeFilesystemImpl.lib
  Building Custom Rule C:/Users/dell/Desktop/mod/my_mod/build/_deps/fmt-src/CMakeLists.txt
  format.cc
  os.cc
  Generating Code...
  fmt.vcxproj -> C:\Users\dell\Desktop\mod\my_mod\build\_deps\fmt-build\RelWithDebInfo\fmt.lib
  Running Codegen
  Building Custom Rule C:/Users/dell/Desktop/mod/my_mod/build/_deps/bindings-src/CMakeLists.txt
  GeneratedSource.cpp
C:\Users\dell\Documents\Geode\loader\include\Geode\c++stl\msvc\xhash.hpp(1799,1): error C2059: syntax error: '}' [C:\U
sers\dell\Desktop\mod\my_mod\build\bindings\GeodeBindings.vcxproj]
C:\Users\dell\Documents\Geode\loader\include\Geode\c++stl\msvc\xhash.hpp(1799,1): error C2143: syntax error: missing '
;' before '}' [C:\Users\dell\Desktop\mod\my_mod\build\bindings\GeodeBindings.vcxproj]
C:\Users\dell\Documents\Geode\loader\include\Geode\c++stl\msvc\umap.hpp(25,22): error C2143: syntax error: missing ';'
 before '{' [C:\Users\dell\Desktop\mod\my_mod\build\bindings\GeodeBindings.vcxproj]
C:\Users\dell\Documents\Geode\loader\include\Geode\c++stl\msvc\umap.hpp(25,22): error C2447: '{': missing function hea
der (old-style formal list?) [C:\Users\dell\Desktop\mod\my_mod\build\bindings\GeodeBindings.vcxproj]
C:\Users\dell\Documents\Geode\loader\include\Geode\c++stl\msvc\umap.hpp(556,1): error C2059: syntax error: '}' [C:\Use
rs\dell\Desktop\mod\my_mod\build\bindings\GeodeBindings.vcxproj]
C:\Users\dell\Documents\Geode\loader\include\Geode\c++stl\msvc\umap.hpp(556,1): error C2143: syntax error: missing ';'
 before '}' [C:\Users\dell\Desktop\mod\my_mod\build\bindings\GeodeBindings.vcxproj]
C:\Users\dell\Documents\Geode\loader\include\Geode\c++stl\msvc\uset.hpp(25,22): error C2143: syntax error: missing ';'
 before '{' [C:\Users\dell\Desktop\mod\my_mod\build\bindings\GeodeBindings.vcxproj]
C:\Users\dell\Documents\Geode\loader\include\Geode\c++stl\msvc\uset.hpp(25,22): error C2447: '{': missing function hea
der (old-style formal list?) [C:\Users\dell\Desktop\mod\my_mod\build\bindings\GeodeBindings.vcxproj]
C:\Users\dell\Documents\Geode\loader\include\Geode\c++stl\msvc\uset.hpp(411,1): error C2059: syntax error: '}' [C:\Use
rs\dell\Desktop\mod\my_mod\build\bindings\GeodeBindings.vcxproj]
C:\Users\dell\Documents\Geode\loader\include\Geode\c++stl\msvc\uset.hpp(411,1): error C2143: syntax error: missing ';'
 before '}' [C:\Users\dell\Desktop\mod\my_mod\build\bindings\GeodeBindings.vcxproj]
E:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.40.33807\include\xtree(23,1): error C2
143: syntax error: missing ';' before '{' [C:\Users\dell\Desktop\mod\my_mod\build\bindings\GeodeBindings.vcxproj]
E:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.40.33807\include\xtree(23,1): error C2
447: '{': missing function header (old-style formal list?) [C:\Users\dell\Desktop\mod\my_mod\build\bindings\GeodeBindi
ngs.vcxproj]
E:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.40.33807\include\map(37,36): error C75
68: argument list missing after assumed function template '_Tree_node' [C:\Users\dell\Desktop\mod\my_mod\build\binding
s\GeodeBindings.vcxproj]
E:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.40.33807\include\map(58,16): error C75
68: argument list missing after assumed function template '_Tree' [C:\Users\dell\Desktop\mod\my_mod\build\bindings\Geo
deBindings.vcxproj]
E:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.40.33807\include\map(58,16): error C20
62: type 'unknown-type' unexpected [C:\Users\dell\Desktop\mod\my_mod\build\bindings\GeodeBindings.vcxproj]
E:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.40.33807\include\map(58,35): error C22
38: unexpected token(s) preceding ';' [C:\Users\dell\Desktop\mod\my_mod\build\bindings\GeodeBindings.vcxproj]
E:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.40.33807\include\map(72,20): error C38
61: '_Tree': identifier not found [C:\Users\dell\Desktop\mod\my_mod\build\bindings\GeodeBindings.vcxproj]
E:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.40.33807\include\map(72,20): error C75
68: argument list missing after assumed function template '_Tree' [C:\Users\dell\Desktop\mod\my_mod\build\bindings\Geo
deBindings.vcxproj]
E:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.40.33807\include\map(72,20): error C37
70: 'unknown-type': is not a valid base class [C:\Users\dell\Desktop\mod\my_mod\build\bindings\GeodeBindings.vcxproj]
E:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.40.33807\include\map(80,36): error C75
68: argument list missing after assumed function template '_Tree' [C:\Users\dell\Desktop\mod\my_mod\build\bindings\Geo
deBindings.vcxproj]
E:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.40.33807\include\map(454,25): error C3
861: '_Tree': identifier not found [C:\Users\dell\Desktop\mod\my_mod\build\bindings\GeodeBindings.vcxproj]
E:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.40.33807\include\map(454,25): error C7
568: argument list missing after assumed function template '_Tree' [C:\Users\dell\Desktop\mod\my_mod\build\bindings\Ge
odeBindings.vcxproj]
E:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.40.33807\include\map(454,25): error C3
770: 'unknown-type': is not a valid base class [C:\Users\dell\Desktop\mod\my_mod\build\bindings\GeodeBindings.vcxproj]
E:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.40.33807\include\map(462,36): error C7
568: argument list missing after assumed function template '_Tree' [C:\Users\dell\Desktop\mod\my_mod\build\bindings\Ge
odeBindings.vcxproj]
E:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.40.33807\include\set(34,36): error C75
68: argument list missing after assumed function template '_Tree_node' [C:\Users\dell\Desktop\mod\my_mod\build\binding
s\GeodeBindings.vcxproj]
E:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.40.33807\include\set(51,20): error C38
61: '_Tree': identifier not found [C:\Users\dell\Desktop\mod\my_mod\build\bindings\GeodeBindings.vcxproj]
E:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.40.33807\include\set(51,20): error C75
68: argument list missing after assumed function template '_Tree' [C:\Users\dell\Desktop\mod\my_mod\build\bindings\Geo
deBindings.vcxproj]
E:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.40.33807\include\set(51,20): error C37
70: 'unknown-type': is not a valid base class [C:\Users\dell\Desktop\mod\my_mod\build\bindings\GeodeBindings.vcxproj]
E:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.40.33807\include\set(59,36): error C75
68: argument list missing after assumed function template '_Tree' [C:\Users\dell\Desktop\mod\my_mod\build\bindings\Geo
deBindings.vcxproj]
E:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.40.33807\include\set(262,25): error C3
861: '_Tree': identifier not found [C:\Users\dell\Desktop\mod\my_mod\build\bindings\GeodeBindings.vcxproj]
E:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.40.33807\include\set(262,25): error C7
568: argument list missing after assumed function template '_Tree' [C:\Users\dell\Desktop\mod\my_mod\build\bindings\Ge
odeBindings.vcxproj]
E:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.40.33807\include\set(262,25): error C3
770: 'unknown-type': is not a valid base class [C:\Users\dell\Desktop\mod\my_mod\build\bindings\GeodeBindings.vcxproj]
E:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.40.33807\include\set(270,36): error C7
568: argument list missing after assumed function template '_Tree' [C:\Users\dell\Desktop\mod\my_mod\build\bindings\Ge
odeBindings.vcxproj]
C:\Users\dell\Documents\Geode\loader\include\Geode\c++stl\msvcstl.hpp(19,39): error C2039: 'unordered_map': is not a m
ember of 'geode::stl' [C:\Users\dell\Desktop\mod\my_mod\build\bindings\GeodeBindings.vcxproj]
C:\Users\dell\Documents\Geode\loader\include\Geode\c++stl\msvcstl.hpp(19,39): error C2061: syntax error: identifier 'u
nordered_map' [C:\Users\dell\Desktop\mod\my_mod\build\bindings\GeodeBindings.vcxproj]
C:\Users\dell\Documents\Geode\loader\include\Geode\c++stl\msvcstl.hpp(25,39): error C2039: 'unordered_set': is not a m
ember of 'geode::stl' [C:\Users\dell\Desktop\mod\my_mod\build\bindings\GeodeBindings.vcxproj]
C:\Users\dell\Documents\Geode\loader\include\Geode\c++stl\msvcstl.hpp(25,39): error C2061: syntax error: identifier 'u
nordered_set' [C:\Users\dell\Desktop\mod\my_mod\build\bindings\GeodeBindings.vcxproj]
E:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.40.33807\include\xsmf_control.h(23,8):
 error C2631: '_Non_trivial_copy': a class or enum cannot be defined in an alias template [C:\Users\dell\Desktop\mod\m
y_mod\build\bindings\GeodeBindings.vcxproj]
E:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.40.33807\include\xsmf_control.h(161,1)
: error C1903: unable to recover from previous error(s); stopping compilation [C:\Users\dell\Desktop\mod\my_mod\build\
bindings\GeodeBindings.vcxproj]
| Fail | CMake build returned code 1

**Comment by hiimjustin000** [comment]
I don't think codegen supports 2.204 anymore

**Comment by hiimjustin000** [comment]
Update your SDK to beta 27 @BurhanYasir123

**Comment by BurhanYasir123** [comment]
i figured it out but   geode build   still does not work even tho i updated
to latest goede sdk version and targeted 2.206 and fixed the json file
because when i opened the game it said old mod.json syntax i still have to
use cmake -B build and cmake --build build --config RelWithDebInfo

**Comment by BurhanYasir123** [comment]
> i figured it out but geode build still does not work even tho i updated to latest goede sdk version and targeted 2.206 and fixed the json file because when i opened the game it said old mod.json syntax i still have to use cmake -B build and cmake --build build --config RelWithDebInfo
