### ISSUE TITLE
Cannot build any geode mod

### ISSUE THREAD

**Issue by Foxiseminger** [geode-sdk/cli#82]
Used geode build on a mod i mas making and this is what i get back:
C:\Users\foxis\OneDrive\Desktop\tp editor>geode build
-- Building for: Visual Studio 17 2022
-- Selecting Windows SDK version 10.0.22621.0 to target Windows 10.0.19045.
-- The C compiler identification is MSVC 19.41.34120.0
-- The CXX compiler identification is MSVC 19.41.34120.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: C:/Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.41.34120/bin/Hostx64/x64/cl.exe - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: C:/Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.41.34120/bin/Hostx64/x64/cl.exe - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found Geode: C:\Users\foxis\all
-- Version: 3.8.1
-- No override path for bindings provided, using CPM to clone default. If you would like to use a separate clone of the bindings repo (for example in order to be able to efficiently change and contribute new bindings) then set GEODE_BINDINGS_REPO_PATH to where you have cloned the repository (system environment variables are supported).
-- CPM: Adding package bindings@ (main)
CMake Warning (dev) at C:/Program Files/CMake/share/cmake-3.30/Modules/FetchContent.cmake:1953 (message):
  Calling FetchContent_Populate(bindings) is deprecated, call
  FetchContent_MakeAvailable(bindings) instead.  Policy CMP0169 can be set to
  OLD to allow FetchContent_Populate(bindings) to be called directly for now,
  but the ability to call it with declared details will be removed completely
  in a future version.
Call Stack (most recent call first):
  build/cmake/CPM_0.39.0.cmake:1008 (FetchContent_Populate)
  build/cmake/CPM_0.39.0.cmake:802 (cpm_fetch_package)
  C:/Users/foxis/all/CMakeLists.txt:78 (CPMAddPackage)
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Looking for ccache/sccache
-- Looking for ccache/sccache - skipped (Visual Studio generator)
Not using a caching compiler (ccache/sccache). It is recommended to install one to improve build times.
We recommend sccache, check its README for installation instructions, normally you can just use your usual package manager (e.g. 'scoop install sccache').
Because of this, PCH will be enabled.
-- Pre-compiled headers - ON
-- Found Geode CLI: C:/Users/foxis/AppData/Local/Microsoft/WinGet/Packages/GeodeSDK.GeodeCLI_Microsoft.Winget.Source_8wekyb3d8bbwe/geode.exe (version 3.0.5)
-- CPM: Adding package json@ (cda9807)
CMake Warning (dev) at C:/Program Files/CMake/share/cmake-3.30/Modules/FetchContent.cmake:1953 (message):
  Calling FetchContent_Populate(json) is deprecated, call
  FetchContent_MakeAvailable(json) instead.  Policy CMP0169 can be set to OLD
  to allow FetchContent_Populate(json) to be called directly for now, but the
  ability to call it with declared details will be removed completely in a
  future version.
Call Stack (most recent call first):
  build/cmake/CPM_0.39.0.cmake:1008 (FetchContent_Populate)
  build/cmake/CPM_0.39.0.cmake:802 (cpm_fetch_package)
  C:/Users/foxis/all/CMakeLists.txt:229 (CPMAddPackage)
This warning is for project developers.  Use -Wno-dev to suppress it.

-- CPM: Adding package fmt@10.2.1 (10.2.1)
CMake Warning (dev) at C:/Program Files/CMake/share/cmake-3.30/Modules/FetchContent.cmake:1953 (message):
  Calling FetchContent_Populate(fmt) is deprecated, call
  FetchContent_MakeAvailable(fmt) instead.  Policy CMP0169 can be set to OLD
  to allow FetchContent_Populate(fmt) to be called directly for now, but the
  ability to call it with declared details will be removed completely in a
  future version.
Call Stack (most recent call first):
  build/cmake/CPM_0.39.0.cmake:1008 (FetchContent_Populate)
  build/cmake/CPM_0.39.0.cmake:802 (cpm_fetch_package)
  C:/Users/foxis/all/CMakeLists.txt:230 (CPMAddPackage)
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Version: 10.2.1
-- Build type: RelWithDebInfo
-- CPM: Adding package TulipHook@ (ddfe8e2)
CMake Warning (dev) at C:/Program Files/CMake/share/cmake-3.30/Modules/FetchContent.cmake:1953 (message):
  Calling FetchContent_Populate(TulipHook) is deprecated, call
  FetchContent_MakeAvailable(TulipHook) instead.  Policy CMP0169 can be set
  to OLD to allow FetchContent_Populate(TulipHook) to be called directly for
  now, but the ability to call it with declared details will be removed
  completely in a future version.
Call Stack (most recent call first):
  build/cmake/CPM_0.39.0.cmake:1008 (FetchContent_Populate)
  build/cmake/CPM_0.39.0.cmake:802 (cpm_fetch_package)
  C:/Users/foxis/all/CMakeLists.txt:259 (CPMAddPackage)
This warning is for project developers.  Use -Wno-dev to suppress it.

-- CPM: TulipHook: Adding package result@ (a97e66b)
CMake Warning (dev) at C:/Program Files/CMake/share/cmake-3.30/Modules/FetchContent.cmake:1953 (message):
  Calling FetchContent_Populate(result) is deprecated, call
  FetchContent_MakeAvailable(result) instead.  Policy CMP0169 can be set to
  OLD to allow FetchContent_Populate(result) to be called directly for now,
  but the ability to call it with declared details will be removed completely
  in a future version.
Call Stack (most recent call first):
  build/cmake/CPM_0.39.0.cmake:1008 (FetchContent_Populate)
  build/cmake/CPM_0.39.0.cmake:802 (cpm_fetch_package)
  build/_deps/tuliphook-src/CMakeLists.txt:23 (CPMAddPackage)
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Performing Test SUPPORTS_W_NO_EVERYTHING
-- Performing Test SUPPORTS_W_NO_EVERYTHING - Failed
-- Downloading Codegen
Set SKIP_BUILDING_CODEGEN to OFF to force codegen to build locally.
-- Downloading Codegen - success
-- Skipping building Codegen
-- Running Codegen
'./Codegen' 'Win64' 'C:/Users/foxis/OneDrive/Desktop/tp editor/build/_deps/bindings-src/bindings/2.206' 'C:/Users/foxis/OneDrive/Desktop/tp editor/build/bindings/bindings'
-- Setting up texturepackeditor
CMake Error at C:/Users/foxis/all/cmake/GeodeFile.cmake:96 (message):
  Mod anekobtw.texture_pack_editor is made for Geode version 3.7.1 but you
  have 3.8.1 SDK installed.  Please change the Geode version in your
  mod.json.
Call Stack (most recent call first):
  CMakeLists.txt:22 (setup_geode_mod)

-- Configuring incomplete, errors occurred!
| Fail | CMake returned code 1
| Info | Tip: deleting the build folder might help :-)
![image](https://github.com/user-attachments/assets/c61e0210-326d-4144-974e-cbafd6aee8b5)

**Comment by Alphalaneous** [comment]
Reading helps:
> Mod anekobtw.texture_pack_editor is made for Geode version 3.7.1 but you have 3.8.1 SDK installed. Please change the Geode version in your mod.json.

**Comment by Foxiseminger** [comment]
gives new error
C:\Users\foxis\OneDrive\Desktop\tp editor>geode build
-- Selecting Windows SDK version 10.0.22621.0 to target Windows 10.0.19045.
-- Found Geode: C:\Users\foxis\all
-- Version: 3.8.1
-- No override path for bindings provided, using CPM to clone default. If you would like to use a separate clone of the bindings repo (for example in order to be able to efficiently change and contribute new bindings) then set GEODE_BINDINGS_REPO_PATH to where you have cloned the repository (system environment variables are supported).
-- CPM: Adding package bindings@ (main)
CMake Warning (dev) at C:/Program Files/CMake/share/cmake-3.30/Modules/FetchContent.cmake:1953 (message):
  Calling FetchContent_Populate(bindings) is deprecated, call
  FetchContent_MakeAvailable(bindings) instead.  Policy CMP0169 can be set to
  OLD to allow FetchContent_Populate(bindings) to be called directly for now,
  but the ability to call it with declared details will be removed completely
  in a future version.
Call Stack (most recent call first):
  build/cmake/CPM_0.39.0.cmake:1008 (FetchContent_Populate)
  build/cmake/CPM_0.39.0.cmake:802 (cpm_fetch_package)
  C:/Users/foxis/all/CMakeLists.txt:78 (CPMAddPackage)
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Looking for ccache/sccache
-- Looking for ccache/sccache - skipped (Visual Studio generator)
Not using a caching compiler (ccache/sccache). It is recommended to install one to improve build times.
We recommend sccache, check its README for installation instructions, normally you can just use your usual package manager (e.g. 'scoop install sccache').
Because of this, PCH will be enabled.
-- Pre-compiled headers - ON
-- Found Geode CLI: C:/Users/foxis/AppData/Local/Microsoft/WinGet/Packages/GeodeSDK.GeodeCLI_Microsoft.Winget.Source_8wekyb3d8bbwe/geode.exe (version 3.0.5)
-- CPM: Adding package json@ (cda9807)
CMake Warning (dev) at C:/Program Files/CMake/share/cmake-3.30/Modules/FetchContent.cmake:1953 (message):
  Calling FetchContent_Populate(json) is deprecated, call
  FetchContent_MakeAvailable(json) instead.  Policy CMP0169 can be set to OLD
  to allow FetchContent_Populate(json) to be called directly for now, but the
  ability to call it with declared details will be removed completely in a
  future version.
Call Stack (most recent call first):
  build/cmake/CPM_0.39.0.cmake:1008 (FetchContent_Populate)
  build/cmake/CPM_0.39.0.cmake:802 (cpm_fetch_package)
  C:/Users/foxis/all/CMakeLists.txt:229 (CPMAddPackage)
This warning is for project developers.  Use -Wno-dev to suppress it.

-- CPM: Adding package fmt@10.2.1 (10.2.1)
CMake Warning (dev) at C:/Program Files/CMake/share/cmake-3.30/Modules/FetchContent.cmake:1953 (message):
  Calling FetchContent_Populate(fmt) is deprecated, call
  FetchContent_MakeAvailable(fmt) instead.  Policy CMP0169 can be set to OLD
  to allow FetchContent_Populate(fmt) to be called directly for now, but the
  ability to call it with declared details will be removed completely in a
  future version.
Call Stack (most recent call first):
  build/cmake/CPM_0.39.0.cmake:1008 (FetchContent_Populate)
  build/cmake/CPM_0.39.0.cmake:802 (cpm_fetch_package)
  C:/Users/foxis/all/CMakeLists.txt:230 (CPMAddPackage)
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Version: 10.2.1
-- Build type: RelWithDebInfo
-- CPM: Adding package TulipHook@ (ddfe8e2)
CMake Warning (dev) at C:/Program Files/CMake/share/cmake-3.30/Modules/FetchContent.cmake:1953 (message):
  Calling FetchContent_Populate(TulipHook) is deprecated, call
  FetchContent_MakeAvailable(TulipHook) instead.  Policy CMP0169 can be set
  to OLD to allow FetchContent_Populate(TulipHook) to be called directly for
  now, but the ability to call it with declared details will be removed
  completely in a future version.
Call Stack (most recent call first):
  build/cmake/CPM_0.39.0.cmake:1008 (FetchContent_Populate)
  build/cmake/CPM_0.39.0.cmake:802 (cpm_fetch_package)
  C:/Users/foxis/all/CMakeLists.txt:259 (CPMAddPackage)
This warning is for project developers.  Use -Wno-dev to suppress it.

-- CPM: TulipHook: Adding package result@ (a97e66b)
CMake Warning (dev) at C:/Program Files/CMake/share/cmake-3.30/Modules/FetchContent.cmake:1953 (message):
  Calling FetchContent_Populate(result) is deprecated, call
  FetchContent_MakeAvailable(result) instead.  Policy CMP0169 can be set to
  OLD to allow FetchContent_Populate(result) to be called directly for now,
  but the ability to call it with declared details will be removed completely
  in a future version.
Call Stack (most recent call first):
  build/cmake/CPM_0.39.0.cmake:1008 (FetchContent_Populate)
  build/cmake/CPM_0.39.0.cmake:802 (cpm_fetch_package)
  build/_deps/tuliphook-src/CMakeLists.txt:23 (CPMAddPackage)
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Downloading Codegen
Set SKIP_BUILDING_CODEGEN to OFF to force codegen to build locally.
-- Downloading Codegen - success
-- Skipping building Codegen
-- Running Codegen
'./Codegen' 'Win64' 'C:/Users/foxis/OneDrive/Desktop/tp editor/build/_deps/bindings-src/bindings/2.206' 'C:/Users/foxis/OneDrive/Desktop/tp editor/build/bindings/bindings'
-- Setting up texturepackeditor
-- Mod anekobtw.texture_pack_editor is compiling for Geode version 3.8.1
CMake Warning at C:/Users/foxis/all/cmake/GeodeFile.cmake:131 (message):
  If you use platform-specific dependencies, upgrade Geode CLI to version
  3.2.0 or greater!
Call Stack (most recent call first):
  CMakeLists.txt:22 (setup_geode_mod)


| Info | Fetching dependency from index
| Info | Dependency found: spaghettdev.betterinputs, version 4.2.0-beta.1
| Info | Downloading dependency
| Info | Success
| Info | Writing dependency to temp file
| Info | Dependency 'spaghettdev.betterinputs' found
| Done | All dependencies resolved
-- Configuring done (13.5s)
-- Generating done (0.2s)
-- Build files have been written to: C:/Users/foxis/OneDrive/Desktop/tp editor/build
MSBuild version 17.11.2+c078802d4 for .NET Framework

  1>Checking Build System
  Building Custom Rule C:/Users/foxis/OneDrive/Desktop/tp editor/build/_deps/fmt-src/CMakeLists.txt
  format.cc
  os.cc
  Generating Code...
  fmt.vcxproj -> C:\Users\foxis\OneDrive\Desktop\tp editor\build\_deps\fmt-build\RelWithDebInfo\fmt.lib
  Running Codegen
  Building Custom Rule C:/Users/foxis/OneDrive/Desktop/tp editor/build/_deps/bindings-src/CMakeLists.txt
  GeneratedSource.cpp
C:\Users\foxis\OneDrive\Desktop\tp editor\build\bindings\bindings\Geode\GeneratedSource.cpp(72,59): error C2661: 'cocos
2d::CCLightning::CCLightning': no overloaded function takes 2 arguments [C:\Users\foxis\OneDrive\Desktop\tp editor\buil
d\bindings\GeodeBindings.vcxproj]
      C:\Users\foxis\OneDrive\Desktop\tp editor\build\bindings\bindings\Geode\GeneratedSource.cpp(72,59):
      while trying to match the argument list '(const geode::CutoffConstructorType, size_t)'

C:\Users\foxis\OneDrive\Desktop\tp editor\build\bindings\bindings\Geode\GeneratedSource.cpp(98,46): error C2661: 'cocos
2d::CCLightning::CCLightning': no overloaded function takes 2 arguments [C:\Users\foxis\OneDrive\Desktop\tp editor\buil
d\bindings\GeodeBindings.vcxproj]
      C:\Users\foxis\OneDrive\Desktop\tp editor\build\bindings\bindings\Geode\GeneratedSource.cpp(98,46):
      while trying to match the argument list '(const geode::CutoffConstructorType, size_t)'

| Fail | CMake build returned code 1

**Comment by Foxiseminger** [comment]
>Mod anekobtw.texture_pack_editor is made for Geode version 3.7.1 but you
have 3.8.1 SDK installed. Please change the Geode version in your
mod.json.
