### ISSUE TITLE
I CANT DOWNLOAD SDK FROM LINUX MINT

### ISSUE THREAD

**Issue by MalikHw** [geode-sdk/cli#83]
![Screenshot_2024-10-23_11-27-07](https://github.com/user-attachments/assets/4bd413a1-565b-47bb-9af0-ba506cd07d53)

PLS TELL ME WTF IS GOIN' ON, IT SAYS "`| Fail | Could not download SDK: SSL error: received early EOF; class=Ssl (16); code=Eof (-20)`"

**Comment by matcool** [comment]
https://stackoverflow.com/questions/42689612/git-clone-error-fatal-early-eofs
