### ISSUE TITLE
CMake fails to configure project on Linux.

### ISSUE THREAD

**Issue by aletschfirn** [geode-sdk/cli#84]
After installing geode SDK and binaries, doing install-linux, and configuring CMake in VS Code, CMake fails to configure project both doing it in VS Code and trying "geode build".
Project itself does get configured without any problems on Windows.

**What I have tried**:
Building using "_geode build_"
Building from VS Code with user-local kit
Updating WinSDK using this command: "_geode sdk install-linux --update-winsdk_"

Logs that I've got from CMake:
[geode.txt](https://github.com/user-attachments/files/17601678/geode.txt)
![Screenshot_2024-11-01_17-19-35](https://github.com/user-attachments/assets/2c113b31-2c38-4b3d-be4b-ae3f48bf00f3)

Logs of updating geode:
![Screenshot_2024-11-01_17-17-00](https://github.com/user-attachments/assets/8f80f7f1-e420-47f8-af86-8afe698b72fb)
![Screenshot_2024-11-01_17-17-24](https://github.com/user-attachments/assets/1db95740-81fa-4815-964b-459ba7bd682f)

Related issue: #72 but steps from it didn't help

**Comment by dankmeme01** [comment]
sounds like your LLVM installation isn't complete, if you type `llvm-ar` or `llvm-nm` in your terminal, does it find those tools or not?

also, what distro is it?

**Comment by aletschfirn** [comment]
Yeah, it was LLVM installation issues... After (re-)installing llvm package(somehow missed it) CMake gives no errors. Thanks for quick response, closing this issue.

**Comment by astra1dev** [comment]
Experienced the same issue on arch, installing llvm fixed it.
imo `llvm` should be added to the instructions [here](https://docs.geode-sdk.org/getting-started/cpp-stuff#linux), so instead of `pacman -S clang lld` have `pacman -S clang lld llvm`. doing so could save other people from having this "issue".
