### ISSUE TITLE
No validation of GD path existing in `geode config setup`

### ISSUE THREAD

**Issue by balt-dev** [geode-sdk/cli#88]
This is something that took me _hours_ to debug on my own.
Within the validation for paths here:
https://github.com/geode-sdk/cli/blob/88740c5e3c418353de87d5affc4c1847c1d0c04e/src/info.rs#L154-L180
There's no actual check that the path _exists_.
This causes numerous errors down the line, and is _really_ something that should be checked.

**Comment by matcool** [comment]
from the code i assume this is linux only?

**Comment by balt-dev** [comment]
Not that I'm aware of, actually. Nothing there actually touches the filesystem - only the path string.
