### ISSUE TITLE
Cannot build any mod

### ISSUE THREAD

**Issue by Danyl0999** [geode-sdk/cli#89]
[main] Building folder: d:/Users/Даня/Documents/Другое/Projects/p1/build 
[main] Configuring project: p1 
[proc] Executing command: "C:\Program Files\CMake\bin\cmake.EXE" -DCMAKE_EXPORT_COMPILE_COMMANDS:BOOL=TRUE --no-warn-unused-cli -SD:/Users/Даня/Documents/Другое/Projects/p1 -Bd:/Users/Даня/Documents/Другое/Projects/p1/build -G "Visual Studio 17 2022" -T host=x64 -A x64
[cmake] Not searching for unused variables given on the command line.
[cmake] -- The C compiler identification is MSVC 19.42.34433.0
[cmake] -- The CXX compiler identification is MSVC 19.42.34433.0
[cmake] -- Detecting C compiler ABI info
[cmake] -- Detecting C compiler ABI info - done
[cmake] -- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2022/BuildTools/VC/Tools/MSVC/14.42.34433/bin/Hostx64/x64/cl.exe - skipped
[cmake] -- Detecting C compile features
[cmake] -- Detecting C compile features - done
[cmake] -- Detecting CXX compiler ABI info
[cmake] -- Detecting CXX compiler ABI info - done
[cmake] -- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2022/BuildTools/VC/Tools/MSVC/14.42.34433/bin/Hostx64/x64/cl.exe - skipped
[cmake] -- Detecting CXX compile features
[cmake] -- Detecting CXX compile features - done
[cmake] -- Found Geode: D:\Users\Даня\Documents\Geode
[cmake] -- Version: 4.0.1
[cmake] -- No override path for bindings provided, using CPM to clone default. If you would like to use a separate clone of the bindings repo (for example in order to be able to efficiently change and contribute new bindings) then set GEODE_BINDINGS_REPO_PATH to where you have cloned the repository (system environment variables are supported).
[cmake] -- CPM: Adding package bindings@ (main)
[cmake] -- Populating bindings
[cmake] -- Selecting Windows SDK version 10.0.22621.0 to target Windows 10.0.22000.
[cmake] -- Configuring done (0.4s)
[cmake] -- Generating done (0.0s)
[cmake] -- Build files have been written to: D:/Users/╨Ф╨░╨╜╤П/Documents/╨Ф╤А╤Г╨│╨╛╨╡/Projects/p1/build/_deps/bindings-subbuild
[cmake] ╨Т╨╡╤А╤Б╨╕╤П MSBuild 17.12.6+db5f6012c ╨┤╨╗╤П .NET Framework
[cmake] 
[cmake]   1>Checking Build System
[cmake]   1>Creating directories for 'bindings-populate'
[cmake]   Performing download step (git clone) for 'bindings-populate'
[cmake]   Cloning into 'bindings-src'...
[cmake]   Your branch is up to date with 'origin/main'.
[cmake]   Already on 'main'
[cmake]   Building Custom Rule D:/Users/╨Ф╨░╨╜╤П/Documents/╨Ф╤А╤Г╨│╨╛╨╡/Projects/p1/build/_deps/bindings-subbuild/CMakeLists.txt
[cmake]   Performing update step for 'bindings-populate'
[cmake]   -- Fetching latest from the remote origin
[cmake]   No patch step for 'bindings-populate'
[cmake]   No configure step for 'bindings-populate'
[cmake]   No build step for 'bindings-populate'
[cmake]   No install step for 'bindings-populate'
[cmake]   No test step for 'bindings-populate'
[cmake]   Completed 'bindings-populate'
[cmake]   Building Custom Rule D:/Users/╨Ф╨░╨╜╤П/Documents/╨Ф╤А╤Г╨│╨╛╨╡/Projects/p1/build/_deps/bindings-subbuild/CMakeLists.txt
[cmake] -- Looking for ccache/sccache
[cmake] -- Looking for ccache/sccache - skipped (Visual Studio generator)
[cmake] Not using a caching compiler (ccache/sccache). It is recommended to install one to improve build times.
[cmake] We recommend sccache, check its README for installation instructions, normally you can just use your usual package manager (e.g. 'scoop install sccache').
[cmake] Because of this, PCH will be enabled.
[cmake] -- Pre-compiled headers - ON
[cmake] CMake Warning at D:/Users/Даня/Documents/Geode/cmake/GeodeFile.cmake:10 (message):
[cmake]   Unable to find Geode CLI
[cmake] Call Stack (most recent call first):
[cmake]   D:/Users/Даня/Documents/Geode/CMakeLists.txt:189 (include)
[cmake] 
[cmake] 
[cmake] -- Found Git: C:/Program Files/Git/cmd/git.exe (found version "2.45.1.windows.1")
[cmake] -- CPM: Adding package result@1.2.1 (v1.2.1 at D:/Users/Даня/Documents/CPM_SOURCE_CACHE/result/28b1b03e0682509636d5e5825265ce2421aac4dc)
[cmake] -- CPM: Adding package json@3.1.0 (v3.1.0 at D:/Users/Даня/Documents/CPM_SOURCE_CACHE/json/258a984b4ade76f160f3780853c026a8a2a6975a)
[cmake] -- {fmt} version: 11.0.2
[cmake] -- Build type: 
[cmake] -- CPM: Adding package fmt@11.0.2 (11.0.2 at D:/Users/Даня/Documents/CPM_SOURCE_CACHE/fmt/cccb77ae9609d2768ed80dd42cec54f77b1f1455)
[cmake] -- CPM: Adding package TulipHook@2.4.1 (v2.4.1 at D:/Users/Даня/Documents/CPM_SOURCE_CACHE/tuliphook/727bc6fdab39f84eb52f1519195d5488a312e77e)
[cmake] -- Performing Test SUPPORTS_W_NO_EVERYTHING
[cmake] -- Performing Test SUPPORTS_W_NO_EVERYTHING - Failed
[cmake] -- Downloading Codegen
[cmake] Set SKIP_BUILDING_CODEGEN to OFF to force codegen to build locally.
[cmake] -- Downloading Codegen - success
[cmake] -- Skipping building Codegen
[cmake] -- Running Codegen
[cmake] './Codegen' 'Win64' 'D:/Users/Даня/Documents/Другое/Projects/p1/build/_deps/bindings-src/bindings/2.2074' 'D:/Users/Даня/Documents/Другое/Projects/p1/build/bindings/bindings'
[cmake] Codegen error: ╨б╨╕╤Б╤В╨╡╨╝╨╡ ╨╜╨╡ ╤Г╨┤╨░╨╡╤В╤Б╤П ╨╜╨░╨╣╤В╨╕ ╤Г╨║╨░╨╖╨░╨╜╨╜╤Л╨╣ ╨┐╤Г╤В╤М.
[cmake] : 'D:\Users\я┐╜я┐╜\Documents\я┐╜я┐╜я┐╜\Projects\p1\build\_deps\bindings-src\bindings\2.2074'
[cmake] CMake Error at build/_deps/bindings-src/CMakeLists.txt:131 (execute_process):
[cmake]   execute_process failed command indexes:
[cmake] 
[cmake]     1: "Child return code: 1"
[cmake] 
[cmake] 
[cmake] 
[cmake] -- Configuring incomplete, errors occurred!
[proc] The command: "C:\Program Files\CMake\bin\cmake.EXE" -DCMAKE_EXPORT_COMPILE_COMMANDS:BOOL=TRUE --no-warn-unused-cli -SD:/Users/Даня/Documents/Другое/Projects/p1 -Bd:/Users/Даня/Documents/Другое/Projects/p1/build -G "Visual Studio 17 2022" -T host=x64 -A x64 exited with code: 1

**Comment by covernts** [comment]
You can't have non ASCII characters in the file name.

**Comment by Danyl0999** [comment]
[proc] Executing command: "C:\Program Files\CMake\bin\cmake.EXE" --version
[proc] Executing command: "C:\Program Files\CMake\bin\cmake.EXE" -E capabilities
[kit] Successfully loaded 14 kits from D:\Users\Даня\AppData\Local\CMakeTools\cmake-tools-kits.json
[variant] Loaded new set of variants
[kit] VS installation instance not found for kit "Visual Studio Build Tools 2019 Release - amd64_x86" - (fb99db6e). It is recommended you re-scan the kits and also remove any user-local entries that are not present anymore on the system.
[kit] VS installation instance not found for kit "Visual Studio Build Tools 2019 Release - x86_amd64" - (fb99db6e). It is recommended you re-scan the kits and also remove any user-local entries that are not present anymore on the system.
[kit] VS installation instance not found for kit "Visual Studio Build Tools 2019 Release - amd64" - (fb99db6e). It is recommended you re-scan the kits and also remove any user-local entries that are not present anymore on the system.
[kit] VS installation instance not found for kit "Visual Studio Build Tools 2019 Release - x86" - (fb99db6e). It is recommended you re-scan the kits and also remove any user-local entries that are not present anymore on the system.
[proc] Executing command: chcp
[main] Configuring project: p1 
[proc] Executing command: "C:\Program Files\CMake\bin\cmake.EXE" -DCMAKE_EXPORT_COMPILE_COMMANDS:BOOL=TRUE --no-warn-unused-cli -SD:/projects/p1 -Bd:/projects/p1/build -G "Visual Studio 17 2022" -T host=x64 -A x64
[cmake] Not searching for unused variables given on the command line.
[cmake] -- The C compiler identification is MSVC 19.42.34433.0
[cmake] -- The CXX compiler identification is MSVC 19.42.34433.0
[cmake] -- Detecting C compiler ABI info
[cmake] -- Detecting C compiler ABI info - done
[cmake] -- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2022/BuildTools/VC/Tools/MSVC/14.42.34433/bin/Hostx64/x64/cl.exe - skipped
[cmake] -- Detecting C compile features
[cmake] -- Detecting C compile features - done
[cmake] -- Detecting CXX compiler ABI info
[cmake] -- Detecting CXX compiler ABI info - done
[cmake] -- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2022/BuildTools/VC/Tools/MSVC/14.42.34433/bin/Hostx64/x64/cl.exe - skipped
[cmake] -- Detecting CXX compile features
[cmake] -- Detecting CXX compile features - done
[cmake] -- Found Geode: D:\Users\Даня\Documents\Geode
[cmake] -- Version: 4.0.1
[cmake] -- No override path for bindings provided, using CPM to clone default. If you would like to use a separate clone of the bindings repo (for example in order to be able to efficiently change and contribute new bindings) then set GEODE_BINDINGS_REPO_PATH to where you have cloned the repository (system environment variables are supported).
[cmake] -- CPM: Adding package bindings@ (main)
[cmake] -- Populating bindings
[cmake] -- Selecting Windows SDK version 10.0.22621.0 to target Windows 10.0.22000.
[cmake] -- Configuring done (0.4s)
[cmake] -- Generating done (0.0s)
[cmake] -- Build files have been written to: D:/projects/p1/build/_deps/bindings-subbuild
[cmake] ╨Т╨╡╤А╤Б╨╕╤П MSBuild 17.12.6+db5f6012c ╨┤╨╗╤П .NET Framework
[cmake] 
[cmake]   1>Checking Build System
[cmake]   1>Creating directories for 'bindings-populate'
[cmake]   Performing download step (git clone) for 'bindings-populate'
[cmake]   Cloning into 'bindings-src'...
[cmake]   Your branch is up to date with 'origin/main'.
[cmake]   Already on 'main'
[cmake]   Building Custom Rule D:/projects/p1/build/_deps/bindings-subbuild/CMakeLists.txt
[cmake]   Performing update step for 'bindings-populate'
[cmake]   -- Fetching latest from the remote origin
[cmake]   No patch step for 'bindings-populate'
[cmake]   No configure step for 'bindings-populate'
[cmake]   No build step for 'bindings-populate'
[cmake]   No install step for 'bindings-populate'
[cmake]   No test step for 'bindings-populate'
[cmake]   Completed 'bindings-populate'
[cmake]   Building Custom Rule D:/projects/p1/build/_deps/bindings-subbuild/CMakeLists.txt
[cmake] -- Looking for ccache/sccache
[cmake] -- Looking for ccache/sccache - skipped (Visual Studio generator)
[cmake] -- Pre-compiled headers - ON
[cmake] Not using a caching compiler (ccache/sccache). It is recommended to install one to improve build times.
[cmake] We recommend sccache, check its README for installation instructions, normally you can just use your usual package manager (e.g. 'scoop install sccache').
[cmake] Because of this, PCH will be enabled.
[cmake] CMake Warning at D:/Users/Даня/Documents/Geode/cmake/GeodeFile.cmake:10 (message):
[cmake]   Unable to find Geode CLI
[cmake] Call Stack (most recent call first):
[cmake]   D:/Users/Даня/Documents/Geode/CMakeLists.txt:189 (include)
[cmake] 
[cmake] 
[cmake] -- Found Git: C:/Program Files/Git/cmd/git.exe (found version "2.45.1.windows.1")
[cmake] -- CPM: Adding package result@1.2.1 (v1.2.1 at D:/Users/Даня/Documents/CPM_SOURCE_CACHE/result/28b1b03e0682509636d5e5825265ce2421aac4dc)
[cmake] -- CPM: Adding package json@3.1.0 (v3.1.0 at D:/Users/Даня/Documents/CPM_SOURCE_CACHE/json/258a984b4ade76f160f3780853c026a8a2a6975a)
[cmake] -- {fmt} version: 11.0.2
[cmake] -- Build type: 
[cmake] -- CPM: Adding package fmt@11.0.2 (11.0.2 at D:/Users/Даня/Documents/CPM_SOURCE_CACHE/fmt/cccb77ae9609d2768ed80dd42cec54f77b1f1455)
[cmake] -- CPM: Adding package TulipHook@2.4.1 (v2.4.1 at D:/Users/Даня/Documents/CPM_SOURCE_CACHE/tuliphook/727bc6fdab39f84eb52f1519195d5488a312e77e)
[cmake] -- Performing Test SUPPORTS_W_NO_EVERYTHING
[cmake] -- Performing Test SUPPORTS_W_NO_EVERYTHING - Failed
[cmake] Set SKIP_BUILDING_CODEGEN to OFF to force codegen to build locally.
[cmake] -- Downloading Codegen
[cmake] -- Downloading Codegen - success
[cmake] -- Skipping building Codegen
[cmake] -- Running Codegen
[cmake] './Codegen' 'Win64' 'D:/projects/p1/build/_deps/bindings-src/bindings/2.2074' 'D:/projects/p1/build/bindings/bindings'
[cmake] CMake Error at D:/Users/Даня/Documents/Geode/cmake/GeodeFile.cmake:74 (message):
[cmake]   setup_geode_mod called, but Geode CLI was not found - Please install CLI:
[cmake]   https://docs.geode-sdk.org/
[cmake] Call Stack (most recent call first):
[cmake]   CMakeLists.txt:22 (setup_geode_mod)
[cmake] 
[cmake] 
[cmake] -- Configuring incomplete, errors occurred!
[proc] The command: "C:\Program Files\CMake\bin\cmake.EXE" -DCMAKE_EXPORT_COMPILE_COMMANDS:BOOL=TRUE --no-warn-unused-cli -SD:/projects/p1 -Bd:/projects/p1/build -G "Visual Studio 17 2022" -T host=x64 -A x64 exited with code: 1
[main] Configuring project: p1 
[proc] Executing command: "C:\Program Files\CMake\bin\cmake.EXE" -DCMAKE_EXPORT_COMPILE_COMMANDS:BOOL=TRUE --no-warn-unused-cli -SD:/projects/p1 -Bd:/projects/p1/build -G "Visual Studio 17 2022" -T host=x64 -A x64
[cmake] Not searching for unused variables given on the command line.
[cmake] -- Found Geode: D:\Users\Даня\Documents\Geode
[cmake] -- Version: 4.0.1
[cmake] -- No override path for bindings provided, using CPM to clone default. If you would like to use a separate clone of the bindings repo (for example in order to be able to efficiently change and contribute new bindings) then set GEODE_BINDINGS_REPO_PATH to where you have cloned the repository (system environment variables are supported).
[cmake] -- CPM: Adding package bindings@ (main)
[cmake] -- Populating bindings
[cmake] -- Selecting Windows SDK version 10.0.22621.0 to target Windows 10.0.22000.
[cmake] -- Configuring done (0.1s)
[cmake] -- Generating done (0.1s)
[cmake] -- Build files have been written to: D:/projects/p1/build/_deps/bindings-subbuild
[cmake] ╨Т╨╡╤А╤Б╨╕╤П MSBuild 17.12.6+db5f6012c ╨┤╨╗╤П .NET Framework
[cmake] 
[cmake]   1>Checking Build System
[cmake]   Performing update step for 'bindings-populate'
[cmake]   -- Fetching latest from the remote origin
[cmake]   Building Custom Rule D:/projects/p1/build/_deps/bindings-subbuild/CMakeLists.txt
[cmake]   No patch step for 'bindings-populate'
[cmake]   No configure step for 'bindings-populate'
[cmake]   No build step for 'bindings-populate'
[cmake]   No install step for 'bindings-populate'
[cmake]   No test step for 'bindings-populate'
[cmake]   Completed 'bindings-populate'
[cmake]   Building Custom Rule D:/projects/p1/build/_deps/bindings-subbuild/CMakeLists.txt
[cmake] -- Looking for ccache/sccache
[cmake] -- Looking for ccache/sccache - skipped (Visual Studio generator)
[cmake] Not using a caching compiler (ccache/sccache). It is recommended to install one to improve build times.
[cmake] We recommend sccache, check its README for installation instructions, normally you can just use your usual package manager (e.g. 'scoop install sccache').
[cmake] Because of this, PCH will be enabled.
[cmake] -- Pre-compiled headers - ON
[cmake] CMake Warning at D:/Users/Даня/Documents/Geode/cmake/GeodeFile.cmake:10 (message):
[cmake]   Unable to find Geode CLI
[cmake] Call Stack (most recent call first):
[cmake]   D:/Users/Даня/Documents/Geode/CMakeLists.txt:189 (include)
[cmake] 
[cmake] 
[cmake] -- CPM: Adding package result@1.2.1 (v1.2.1 at D:/Users/Даня/Documents/CPM_SOURCE_CACHE/result/28b1b03e0682509636d5e5825265ce2421aac4dc)
[cmake] -- CPM: Adding package json@3.1.0 (v3.1.0 at D:/Users/Даня/Documents/CPM_SOURCE_CACHE/json/258a984b4ade76f160f3780853c026a8a2a6975a)
[cmake] -- {fmt} version: 11.0.2
[cmake] -- Build type: 
[cmake] -- CPM: Adding package fmt@11.0.2 (11.0.2 at D:/Users/Даня/Documents/CPM_SOURCE_CACHE/fmt/cccb77ae9609d2768ed80dd42cec54f77b1f1455)
[cmake] -- CPM: Adding package TulipHook@2.4.1 (v2.4.1 at D:/Users/Даня/Documents/CPM_SOURCE_CACHE/tuliphook/727bc6fdab39f84eb52f1519195d5488a312e77e)
[cmake] -- Downloading Codegen
[cmake] Set SKIP_BUILDING_CODEGEN to OFF to force codegen to build locally.
[cmake] -- Downloading Codegen - success
[cmake] -- Skipping building Codegen
[cmake] -- Running Codegen
[cmake] './Codegen' 'Win64' 'D:/projects/p1/build/_deps/bindings-src/bindings/2.2074' 'D:/projects/p1/build/bindings/bindings'
[cmake] CMake Error at D:/Users/Даня/Documents/Geode/cmake/GeodeFile.cmake:74 (message):
[cmake]   setup_geode_mod called, but Geode CLI was not found - Please install CLI:
[cmake]   https://docs.geode-sdk.org/
[cmake] Call Stack (most recent call first):
[cmake]   CMakeLists.txt:22 (setup_geode_mod)
[cmake] 
[cmake] 
[cmake] -- Configuring incomplete, errors occurred!
[proc] The command: "C:\Program Files\CMake\bin\cmake.EXE" -DCMAKE_EXPORT_COMPILE_COMMANDS:BOOL=TRUE --no-warn-unused-cli -SD:/projects/p1 -Bd:/projects/p1/build -G "Visual Studio 17 2022" -T host=x64 -A x64 exited with code: 1

**Comment by Danyl0999** [comment]
[main] Building folder: d:/projects/p1/build 
[main] Configuring project: p1 
[proc] Executing command: "C:\Program Files\CMake\bin\cmake.EXE" -DCMAKE_EXPORT_COMPILE_COMMANDS:BOOL=TRUE --no-warn-unused-cli -SD:/projects/p1 -Bd:/projects/p1/build -G "Visual Studio 17 2022" -T host=x64 -A x64
[cmake] Not searching for unused variables given on the command line.
[cmake] -- The C compiler identification is MSVC 19.42.34433.0
[cmake] -- The CXX compiler identification is MSVC 19.42.34433.0
[cmake] -- Detecting C compiler ABI info
[cmake] -- Detecting C compiler ABI info - done
[cmake] -- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2022/BuildTools/VC/Tools/MSVC/14.42.34433/bin/Hostx64/x64/cl.exe - skipped
[cmake] -- Detecting C compile features
[cmake] -- Detecting C compile features - done
[cmake] -- Detecting CXX compiler ABI info
[cmake] -- Detecting CXX compiler ABI info - done
[cmake] -- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2022/BuildTools/VC/Tools/MSVC/14.42.34433/bin/Hostx64/x64/cl.exe - skipped
[cmake] -- Detecting CXX compile features
[cmake] -- Detecting CXX compile features - done
[cmake] -- Found Geode: D:\Users\Даня\Documents\Geode
[cmake] -- Version: 4.0.1
[cmake] -- No override path for bindings provided, using CPM to clone default. If you would like to use a separate clone of the bindings repo (for example in order to be able to efficiently change and contribute new bindings) then set GEODE_BINDINGS_REPO_PATH to where you have cloned the repository (system environment variables are supported).
[cmake] -- CPM: Adding package bindings@ (main)
[cmake] -- Populating bindings
[cmake] -- Selecting Windows SDK version 10.0.22621.0 to target Windows 10.0.22000.
[cmake] -- Configuring done (0.4s)
[cmake] -- Generating done (0.0s)
[cmake] -- Build files have been written to: D:/projects/p1/build/_deps/bindings-subbuild
[cmake] ╨Т╨╡╤А╤Б╨╕╤П MSBuild 17.12.6+db5f6012c ╨┤╨╗╤П .NET Framework
[cmake] 
[cmake]   1>Checking Build System
[cmake]   1>Creating directories for 'bindings-populate'
[cmake]   Performing download step (git clone) for 'bindings-populate'
[cmake]   Cloning into 'bindings-src'...
[cmake]   Your branch is up to date with 'origin/main'.
[cmake]   Already on 'main'
[cmake]   Building Custom Rule D:/projects/p1/build/_deps/bindings-subbuild/CMakeLists.txt
[cmake]   Performing update step for 'bindings-populate'
[cmake]   -- Fetching latest from the remote origin
[cmake]   No patch step for 'bindings-populate'
[cmake]   No configure step for 'bindings-populate'
[cmake]   No build step for 'bindings-populate'
[cmake]   No install step for 'bindings-populate'
[cmake]   No test step for 'bindings-populate'
[cmake]   Completed 'bindings-populate'
[cmake]   Building Custom Rule D:/projects/p1/build/_deps/bindings-subbuild/CMakeLists.txt
[cmake] -- Looking for ccache/sccache
[cmake] -- Looking for ccache/sccache - skipped (Visual Studio generator)
[cmake] -- Pre-compiled headers - ON
[cmake] Not using a caching compiler (ccache/sccache). It is recommended to install one to improve build times.
[cmake] We recommend sccache, check its README for installation instructions, normally you can just use your usual package manager (e.g. 'scoop install sccache').
[cmake] Because of this, PCH will be enabled.
[cmake] CMake Warning at D:/Users/Даня/Documents/Geode/cmake/GeodeFile.cmake:10 (message):
[cmake]   Unable to find Geode CLI
[cmake] Call Stack (most recent call first):
[cmake]   D:/Users/Даня/Documents/Geode/CMakeLists.txt:189 (include)
[cmake] 
[cmake] 
[cmake] -- Found Git: C:/Program Files/Git/cmd/git.exe (found version "2.45.1.windows.1")
[cmake] -- CPM: Adding package result@1.2.1 (v1.2.1 at D:/Users/Даня/Documents/CPM_SOURCE_CACHE/result/28b1b03e0682509636d5e5825265ce2421aac4dc)
[cmake] -- CPM: Adding package json@3.1.0 (v3.1.0 at D:/Users/Даня/Documents/CPM_SOURCE_CACHE/json/258a984b4ade76f160f3780853c026a8a2a6975a)
[cmake] -- {fmt} version: 11.0.2
[cmake] -- Build type: 
[cmake] -- CPM: Adding package fmt@11.0.2 (11.0.2 at D:/Users/Даня/Documents/CPM_SOURCE_CACHE/fmt/cccb77ae9609d2768ed80dd42cec54f77b1f1455)
[cmake] -- CPM: Adding package TulipHook@2.4.1 (v2.4.1 at D:/Users/Даня/Documents/CPM_SOURCE_CACHE/tuliphook/727bc6fdab39f84eb52f1519195d5488a312e77e)
[cmake] -- Performing Test SUPPORTS_W_NO_EVERYTHING
[cmake] -- Performing Test SUPPORTS_W_NO_EVERYTHING - Failed
[cmake] Set SKIP_BUILDING_CODEGEN to OFF to force codegen to build locally.
[cmake] -- Downloading Codegen
[cmake] -- Downloading Codegen - success
[cmake] -- Skipping building Codegen
[cmake] -- Running Codegen
[cmake] './Codegen' 'Win64' 'D:/projects/p1/build/_deps/bindings-src/bindings/2.2074' 'D:/projects/p1/build/bindings/bindings'
[cmake] CMake Error at D:/Users/Даня/Documents/Geode/cmake/GeodeFile.cmake:74 (message):
[cmake]   setup_geode_mod called, but Geode CLI was not found - Please install CLI:
[cmake]   https://docs.geode-sdk.org/
[cmake] Call Stack (most recent call first):
[cmake]   CMakeLists.txt:22 (setup_geode_mod)
[cmake] 
[cmake] 
[cmake] -- Configuring incomplete, errors occurred!
[proc] The command: "C:\Program Files\CMake\bin\cmake.EXE" -DCMAKE_EXPORT_COMPILE_COMMANDS:BOOL=TRUE --no-warn-unused-cli -SD:/projects/p1 -Bd:/projects/p1/build -G "Visual Studio 17 2022" -T host=x64 -A x64 exited with code: 1
